"""add knowledge retrieval

Revision ID: 693022e640d1
Revises: 81a6f9440f09
Create Date: 2026-06-22 11:56:58.809280
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "693022e640d1"
down_revision: str | None = "81a6f9440f09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("product_area", sa.String(length=60), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_path", sa.String(length=500), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by", sa.String(length=120), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_product_area"),
        "knowledge_documents",
        ["product_area"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_status"), "knowledge_documents", ["status"], unique=False
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("document_id", sa.String(length=120), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(dim=384), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["knowledge_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index"),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_document_id"), "knowledge_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "benchmark_cases",
        sa.Column("ticket_id", sa.String(length=30), nullable=False),
        sa.Column("dataset_version", sa.String(length=30), nullable=False),
        sa.Column("expected_category", sa.String(length=60), nullable=False),
        sa.Column("acceptable_root_causes", sa.JSON(), nullable=False),
        sa.Column("required_sources", sa.JSON(), nullable=False),
        sa.Column("prohibited_claims", sa.JSON(), nullable=False),
        sa.Column("allowed_tools", sa.JSON(), nullable=False),
        sa.Column("expected_actions", sa.JSON(), nullable=False),
        sa.Column("escalation_required", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("benchmark_cases")
    op.drop_index(op.f("ix_knowledge_chunks_document_id"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_documents_status"), table_name="knowledge_documents")
    op.drop_index(op.f("ix_knowledge_documents_product_area"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    # ### end Alembic commands ###
